'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first  terms will be:
    
1,2,3,5,8,13,21,24,55,89,...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

fib_list = []

def fibonacci_number(n):
    if n == 0 or n == 1:
        return 1
    else:
        return fibonacci_number(n-1) + fibonacci_number(n-2)

def append_fib_list():
    value = 0
    counter = 0
    while value <= 4000000:
        value = fibonacci_number(counter)

        fib_list.append(value)
        counter += 1


def sum_even_valued_terms():
    sum = 0
    for v in fib_list:
        if v % 2 == 0:
            sum += v

    return sum

append_fib_list()
print(f'Sum is: {sum_even_valued_terms()}')

